/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };
const sidebars = {
  "apiSidebar": [
    {
      "type": "autogenerated",
      "dirName": "api"
    }
  ],
  "tutorialSidebar": [
    {
      "label": "Getting started",
      "type": "category",
      "items": [
        "quickstart",
        "development",
        "settings/global",
        "settings/navigation"
      ],
      "link": {
        "type": "generated-index",
        "title": "Getting started"
      }
    },
    {
      "label": "Writing content",
      "type": "category",
      "items": [
        "code-blocks",
        "headers-and-text",
        "images-videos-and-embeds",
        "lists-and-tables",
        "page-titles-and-metadata",
        "reusable-snippets"
      ],
      "link": {
        "type": "generated-index",
        "title": "Writing content"
      }
    },
    {
      "label": "API Reference",
      "type": "category",
      "items": [
        "interactive-playground",
        {
          "label": "Using OpenAPI",
          "type": "category",
          "items": [
            "openapi-setup",
            "writing-openapi",
            "advanced-features"
          ],
          "link": {
            "type": "generated-index",
            "title": "Using OpenAPI"
          }
        },
        {
          "label": "Using MDX",
          "type": "category",
          "items": [
            "mdx-setup",
            "authentication"
          ],
          "link": {
            "type": "generated-index",
            "title": "Using MDX"
          }
        }
      ],
      "link": {
        "type": "generated-index",
        "title": "API Reference"
      }
    },
    {
      "label": "Configurations",
      "type": "category",
      "items": [
        "settings/custom-domain",
        "settings/add-members",
        "settings/github",
        "settings/gitlab",
        "settings/broken-links",
        "settings/seo",
        "settings/authentication",
        "settings/versioning"
      ],
      "link": {
        "type": "generated-index",
        "title": "Configurations"
      }
    }
  ]
};

export default sidebars;