
const { isGeneratedIndex, isAutoGenerated } = require('../../lib/skelo-utils');

describe('skelo-utils', () => {
    
    describe('isGeneratedIndex', () => {

        test('should return true if the item has a generated_index property set to true', () => {
            
            expect(isGeneratedIndex({generated_index: true})).toBe(true);
        })
        test('should return true if the item has a generated_index property set to "true"', () => {
            expect(isGeneratedIndex({generated_index: 'true'})).toBe(true);
        })

        test('should return false if the item has a generated_index property set to false', () => {
            expect(isGeneratedIndex({generated_index: false})).toBe(false);
        })

        test('should return false if the item has no generated_index property', () => {
            expect(isGeneratedIndex({})).toBe(false);
        })
    })

    describe('isAutoGenerated', () => {


        test('should return true if the item has a autogenerated property set to true', () => {
            
            expect(isAutoGenerated({autogenerated: true})).toBe(true);
        })
        test('should return true if the item has a autogenerated property set to "true"', () => {
            expect(isAutoGenerated({autogenerated: 'true'})).toBe(true);
        })

        test('should return false if the item has a autogenerated property set to false', () => {
            expect(isAutoGenerated({autogenerated: false})).toBe(false);
        })

        test('should return false if the item has no autogenerated property', () => {
            expect(isAutoGenerated({})).toBe(false);
        })


    })
})