/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };
const sidebars = {
  "skeloDocsSidebar": [
    {
      "type": "category",
      "label": "Introduction",
      "items": [
        {
          "type": "category",
          "label": "Getting Started",
          "items": [
            "skelodocs/installation",
            "skelodocs/running-from-the-command-line",
            {
              "type": "category",
              "label": "Outline files",
              "items": [
                "skelodocs/outline-file-location",
                "skelodocs/outline-file-schema"
              ],
              "link": {
                "type": "generated-index",
                "title": "Outline files"
              }
            }
          ],
          "link": {
            "type": "generated-index",
            "title": "Getting Started"
          }
        }
      ],
      "link": {
        "type": "generated-index",
        "title": "Introduction"
      }
    },
    "skelodocs/guides"
  ],
  "standardSidebar": [],
  "updatesSidebar": [],
  "jestDocsSidebar": [
    {
      "type": "category",
      "label": "Introduction",
      "items": [
        "jestdocs/getting-started",
        "jestdocs/using-matchers",
        "jestdocs/testing-asynchronous-code",
        "jestdocs/setup-and-teardown",
        "jestdocs/mock-functions",
        "jestdocs/jest-platform",
        "jestdocs/jest-community",
        "jestdocs/more-resources"
      ]
    },
    {
      "type": "category",
      "label": "Guides",
      "items": [
        "jestdocs/snapshot-testing",
        "jestdocs/an-async-example",
        "jestdocs/timer-mocks",
        "jestdocs/manual-mocks",
        "jestdocs/es6-class-mocks",
        "jestdocs/bypassing-module-mocks",
        "jestdocs/ecmascript-modules",
        "jestdocs/using-with-webpack",
        "jestdocs/using-with-puppeteer",
        "jestdocs/using-with-mongodb",
        "jestdocs/using-with-dynamodb",
        "jestdocs/dom-manipulation",
        "jestdocs/watch-plugins",
        "jestdocs/migrating-to-jest",
        "jestdocs/troubleshooting",
        "jestdocs/architecture"
      ]
    },
    {
      "type": "category",
      "label": "Frameworks Guides",
      "items": [
        "jestdocs/testing-react-apps",
        "jestdocs/testing-react-native-apps",
        "jestdocs/testing-web-frameworks"
      ]
    },
    {
      "type": "category",
      "label": "Upgrade Guides",
      "items": [
        "jestdocs/from-v28-to-v29"
      ]
    }
  ],
  "apiSidebar": [
    "api",
    "expect",
    "mock-functions",
    "the-jest-object",
    "configuring-jest",
    "jest-cli-options",
    "environment-variables",
    "code-transformation"
  ],
  "docsSidebar": [
    {
      "type": "category",
      "label": "Introduction",
      "items": [
        "getting-started",
        "fundamental-concepts"
      ]
    }
  ],
  "secondSidebar": [
    "secondsidebar/overview"
  ],
  "tutorialSidebar": [
    "tutorial/introduction",
    {
      "type": "category",
      "label": "Getting Started",
      "items": [
        "tutorial/installation",
        "tutorial/configuration",
        "tutorial/playground",
        "tutorial/typescript-support"
      ],
      "link": {
        "type": "generated-index",
        "title": "Getting Started"
      }
    }
  ]
};

export default sidebars;